package pl.lipiec.View;

import pl.lipiec.Model.TableModel;
import pl.lipiec.Controllers.MainPanelController;

/**
 * Class representing view of user panel after he log in the program.
 * @author Krzysztof Lipiec
 * @version 1.0
 */
public class MainPanel extends javax.swing.JPanel {

    
    /**
     * Creates new form MainPanel
     */

    private MainPanelController controller = new MainPanelController();
    
    public MainPanel() {
        initComponents();
        jTable1.setModel(new TableModel(controller.getAccounts()));
        controller.setTableModel((TableModel) jTable1.getModel());
    }
    
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        addNewRowButton = new javax.swing.JButton();
        deleteRowSelectedButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(600, 400));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jTable1);

        addNewRowButton.setText("Dodaj nowy");
        addNewRowButton.setActionCommand("jButton1");
        addNewRowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewRowButtonActionPerformed(evt);
            }
        });

        deleteRowSelectedButton.setText("Usuń wybrany");
        deleteRowSelectedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteRowSelectedButtonActionPerformed(evt);
            }
        });

        saveButton.setText("Zapisz");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addNewRowButton)
                        .addGap(56, 56, 56)
                        .addComponent(deleteRowSelectedButton)
                        .addGap(56, 56, 56)
                        .addComponent(saveButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(addNewRowButton)
                    .addComponent(deleteRowSelectedButton)
                    .addComponent(saveButton))
                .addGap(34, 34, 34))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addNewRowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewRowButtonActionPerformed
        controller.addNewRow((TableModel) jTable1.getModel());
    }//GEN-LAST:event_addNewRowButtonActionPerformed

    private void deleteRowSelectedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteRowSelectedButtonActionPerformed
        var selectedRow = jTable1.getSelectedRow();
        controller.deleteSelectedRow(selectedRow);
    }//GEN-LAST:event_deleteRowSelectedButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        controller.saveData((TableModel) jTable1.getModel());
    }//GEN-LAST:event_saveButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNewRowButton;
    private javax.swing.JButton deleteRowSelectedButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
